# fly.toml app configuration file for multi-vendor-backend-free

app = "multi-vendor-backend-free"
primary_region = "fra"  # Frankfurt, closest to Malawi

[build]

[env]
  PORT = "5000"
  DATABASE_URL = "postgresql://neondb_owner:npg_ypRkjgEQ67JD@ep-shiny-haze-a97m5pt8-pooler.gwc.azure.neon.tech/neondb?sslmode=require&channel_binding=require"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
